# Generated by Django 4.2.1 on 2023-05-14 15:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0002_dishmodel_description_dishmodel_menu_category_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dishmodel",
            name="serving_time",
        ),
        migrations.RemoveField(
            model_name="ordermodel",
            name="serving_time",
        ),
        migrations.AddField(
            model_name="table",
            name="state",
            field=models.CharField(
                choices=[("Empty", "Empty"), ("Dining", "Dining")],
                default="Empty",
                max_length=50,
            ),
        ),
    ]
