# Generated by Django 4.2.1 on 2023-05-14 16:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0003_remove_dishmodel_serving_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="order_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="order",
            name="menu_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="base.menuitem"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="table",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="base.table"
            ),
        ),
    ]
