# Generated by Django 4.2.1 on 2023-05-14 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0004_order_order_time_alter_order_menu_item_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="menu_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="base.dishmodel"
            ),
        ),
    ]
