# Generated by Django 4.2.1 on 2023-05-14 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0005_alter_order_menu_item"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="order_time",
        ),
        migrations.RemoveField(
            model_name="table",
            name="state",
        ),
        migrations.AddField(
            model_name="dishmodel",
            name="serving_time",
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name="ordermodel",
            name="serving_time",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="order",
            name="table",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="base.table"
            ),
        ),
    ]
