# Generated by Django 4.2.1 on 2023-05-14 16:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0006_remove_order_order_time_remove_table_state_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dishmodel",
            name="serving_time",
        ),
        migrations.RemoveField(
            model_name="ordermodel",
            name="serving_time",
        ),
    ]
