# Generated by Django 4.2.1 on 2023-05-14 17:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0008_delete_book_delete_detailsmodel_remove_note_user_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MenuItem",
        ),
        migrations.AddField(
            model_name="order",
            name="order_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="table",
            name="state",
            field=models.CharField(
                choices=[("Empty", "Empty"), ("Dining", "Dining")],
                default="Empty",
                max_length=50,
            ),
        ),
    ]
