# Generated by Django 4.2.1 on 2023-09-23 13:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0009_delete_menuitem_order_order_time_table_state"),
    ]

    operations = [
        migrations.CreateModel(
            name="WaiterModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=50, unique=True)),
                ("password", models.CharField(max_length=50)),
                ("contact_no", models.CharField(max_length=10)),
                ("is_active", models.BooleanField(default=False)),
            ],
        ),
    ]
