# Generated by Django 4.2.1 on 2023-09-23 14:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0010_waitermodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="table",
            name="order_state",
            field=models.CharField(
                choices=[
                    ("cook", "Cook"),
                    ("prepared", "Prepared"),
                    ("order", "Order"),
                    ("served", "Served"),
                ],
                default="Order",
                max_length=50,
            ),
        ),
    ]
