# Generated by Django 4.2.1 on 2023-09-25 11:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0012_alter_table_order_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="table",
            name="order_state",
            field=models.CharField(
                choices=[
                    ("All", "All"),
                    ("Order", "Order"),
                    ("Cook", "Cook"),
                    ("Prepared", "Prepared"),
                    ("Served", "Served"),
                ],
                default="All",
                max_length=50,
            ),
        ),
    ]
