# Generated by Django 4.2.1 on 2023-09-25 14:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0014_orderbackupmodel"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderbackupmodel",
            name="order_date",
        ),
        migrations.RemoveField(
            model_name="orderbackupmodel",
            name="quantity",
        ),
        migrations.RemoveField(
            model_name="orderbackupmodel",
            name="user",
        ),
        migrations.AddField(
            model_name="orderbackupmodel",
            name="counter",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="orderbackupmodel",
            name="order_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="orderbackupmodel",
            name="table",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="base.table"
            ),
        ),
        migrations.CreateModel(
            name="ConfirmedOrderModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("counter", models.IntegerField(default=0)),
                ("order_time", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "menu_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="base.dishmodel"
                    ),
                ),
                (
                    "table",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base.table",
                    ),
                ),
            ],
        ),
    ]
