# Generated by Django 4.2.1 on 2023-10-07 10:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0015_remove_orderbackupmodel_order_date_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ConfirmedOrderModel",
            new_name="CustomerOrderModel",
        ),
    ]
